### ISSUE TITLE
Invertir proyecto

### ISSUE THREAD

**Issue by ejalarcon** [UNIR-Trabajo-Final-Experto-2020/Alastria-HouseFunding-TFE#6]
- Quitar cuentaInversor como parámetro y obtenerla con el msg.sender
- Validar que el promotor, proyecto (esProyectoValido) e inversor están registrados.
- Se transfieren numeroTokens de cuentaInversor a cuentaProyecto: (descomentar transferFrom y emitir evento).
- Actualizamos el número de token que un inversor tiene en un proyecto (quitar += por =)
- Validar que un inversor no haya invertido previamente.
- Validar que el proyecto está en estado INICIADO (cambiar nombre por EN_FINANCIACION)
- Validar que el tokensGoal + el numeroTokens a invertir no supera tokensGoal. 
- En caso de superarlo el tokensGoal, emitir evento TokenDisponibles, informando de la cantidad  de tokens que se pueden invertir.
- En caso de llegar al tokensGoal, se debe cambiar el estado del proyecto a EN_PROGRESO (construcción del inmueble).

**Comment by juanjotg** [comment]
Para estos dos puntos:

- Validar que el tokensGoal + el numeroTokens a invertir no supera tokensGoal.

- En caso de superarlo el tokensGoal, emitir evento TokenDisponibles, informando de la cantidad de tokens que se pueden invertir.

Al final lo que vamos hacer es que, no se hace la validación (require) de "tokenGoal + numToken que se quieren invertir por parte del inversor sea mayor al tokenGoal" y si esto ocurre, se emite un evento "TokenPtesCompletarProyecto", para informar al inversor, de la cantidad de token que quedan ptes para llegar al tokenGoal y que será el máximo que se puede invertir en ese momento.
